### PR TITLE
Adding support for Galois field orders up to 31

### PR DESCRIPTION
**Pull request by Ben-Mathews**
The version of bch.c that python-bchlib wraps only supports GF orders up to 15.  This change extends support for GF orders up to 31.

### CODE REVIEW

**Comment by jkent** [comment]
Hi Ben,

Since the change simple enough, do you think you can get this into the Linux kernel?  I don't want to diverge from the kernel code if I don't have to.

Thanks for your contribution!

**Comment by Ben-Mathews** [comment]
Hi Jeff - Sorry for the delay.  That makes complete sense and I figured that would be your response but wanted to make you aware of the change.  Thank you for publishing such a useful Python wrapper!  I'll submit the change to the kernel and hopefully they'll accept it.

**Comment by jkent** [comment]
Let me know if they reject it, I'll merge in that case!

**Comment by jkent** [comment]
Since this has never made it upstream, I'm going to go ahead and merge it so you get credit in the next major release.

**Pull request merged**
